#!/usr/bin/env python
"""Generate the Cursor install artifacts for quant-swarm.

Writes:
  .cursor/mcp.json       — the stdio mcpServers block (checked-in example)
  .cursor/DEEPLINKS.md   — cursor://…/mcp/install deeplinks for all three
                           servers (config is base64 of the stdio config,
                           URL-encoded), so the links cannot drift from the
                           JSON.

Run:  python scripts/make_deeplinks.py
"""
from __future__ import annotations

import base64
import json
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
CURSOR_DIR = ROOT / ".cursor"

SERVERS = {
    "swarm-data": "swarm-data-mcp",
    "swarm-warden": "swarm-warden-mcp",
    "swarm-gym": "swarm-gym-mcp",
}

TOKEN_PLACEHOLDER = "<token from https://1.21initiative.com/>"


def stdio_config(server_script: str) -> dict:
    return {
        "command": "uvx",
        "args": ["--from", "quant-swarm", server_script],
        "env": {"SWARM_MCP_ACCESS_TOKEN": TOKEN_PLACEHOLDER},
    }


def deeplink(name: str, server_script: str) -> str:
    cfg = json.dumps(stdio_config(server_script), separators=(",", ":"))
    encoded = base64.b64encode(cfg.encode("utf-8")).decode("ascii")
    return (
        "cursor://anysphere.cursor-deeplink/mcp/install"
        f"?name={quote(name, safe='')}&config={quote(encoded, safe='')}"
    )


def main() -> None:
    CURSOR_DIR.mkdir(exist_ok=True)

    mcp_json = {"mcpServers": {n: stdio_config(s) for n, s in SERVERS.items()}}
    (CURSOR_DIR / "mcp.json").write_text(
        json.dumps(mcp_json, indent=2) + "\n", encoding="utf-8"
    )

    lines = [
        "# Cursor deeplinks — quant-swarm",
        "",
        "Generated by `scripts/make_deeplinks.py` — do not edit by hand.",
        "Each link installs one server with the placeholder token; set your real",
        f"token in Cursor's MCP settings after installing (free at",
        "https://1.21initiative.com/mcp/).",
        "",
    ]
    for name, script in SERVERS.items():
        link = deeplink(name, script)
        lines.append(f"- **{name}** ({script}): [add to Cursor]({link})")
        lines.append(f"  `{link}`")
    (CURSOR_DIR / "DEEPLINKS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print("wrote .cursor/mcp.json and .cursor/DEEPLINKS.md")
    for name, script in SERVERS.items():
        print(f"{name}: {deeplink(name, script)}")


if __name__ == "__main__":
    main()
